In [10]:
import numpy as np
import json
import sys
import os
import h5py
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
from matplotlib import rc
rc('font',**{'family':'serif','serif':['Times New Roman']})
rc('text', usetex=True)
rc('font', size=18)

## Get cpu time files

In [17]:
def get_cfldict(case_path, methods, cfls, reso, params):
    array3d = np.zeros([len(methods),len(cfls),len(params)])

    ii = 0 
    for case in methods:
        jj = 0
        for cfl in cfls:
            f=open(str(case_path + '/cfl_'+str(cfl)+'/'+str(reso)+'/'+case+'/errors.dat'))
            for line in f:
                if 'cpu_' in line:
                    array3d[ii,jj,0] = float(line.split('=')[1])
                if 'adv_' in line:
                    array3d[ii,jj,1] = float(line.split('=')[1])
                if 'rec_' in line:
                    array3d[ii,jj,2] = float(line.split('=')[1])
                if 'cor_' in line:
                    array3d[ii,jj,3] = float(line.split('=')[1])
            jj +=1
        ii += 1
    
    methodcfl = {}
    for j in range(len(methods)):
        arr = array3d[j,:,:]
        pd_arr = pd.DataFrame(
            arr, 
            columns = params,
            index = cfls
            )
        methodcfl.update({str(methods[j]):pd_arr})
        
    paramcfl = {}
    for j in range(len(params)):
        arr = np.transpose(array3d[:,:,j])
        pd_arr = pd.DataFrame(
            arr, 
            columns = methods,
            index = cfls
            )
        paramcfl.update({str(params[j]):pd_arr})

        
    return paramcfl,methodcfl

def get_resodict(case_path, methods, cfl, resos, params):
    array3d = np.zeros([len(methods),len(resos),len(params)])

    ii = 0 
    for case in methods:
        jj = 0
        for reso in resos:
            f=open(str(case_path + '/cfl_'+str(cfl)+'/'+str(reso)+'/'+case+'/errors.dat'))
            for line in f:
                if 'cpu_' in line:
                    array3d[ii,jj,0] = float(line.split('=')[1])
                if 'adv_' in line:
                    array3d[ii,jj,1] = float(line.split('=')[1])
                if 'rec_' in line:
                    array3d[ii,jj,2] = float(line.split('=')[1])
                if 'cor_' in line:
                    array3d[ii,jj,3] = float(line.split('=')[1])
            jj +=1
        ii += 1
    
    methodreso = {}
    for j in range(len(methods)):
        arr = array3d[j,:,:]
        pd_arr = pd.DataFrame(
            arr, 
            columns = params,
            index = resos
            )
        methodreso.update({str(methods[j]):pd_arr})
        
    paramreso = {}
    for j in range(len(params)):
        arr = np.transpose(array3d[:,:,j])
        pd_arr = pd.DataFrame(
            arr, 
            columns = methods,
            index = resos
            )
        paramreso.update({str(params[j]):pd_arr})

    return paramreso, methodreso

In [23]:
methods = ["EI","LE","EILE3D","EILE3DS","EIEALE","WY"]
params = ["cpu","adv","rec","cor"]
resos = [16,32,64,128]
cfls = [0.05,0.1,0.15,0.2,0.25,0.3,0.5]
cfl = 0.5
reso = 64
case_path_z = 'Zalesak3D'

In [24]:
paramcfl_z,  methodcfl_z  = get_cfldict(case_path_z, methods, cfls, reso, params)
paramreso_z, methodreso_z = get_resodict(case_path_z, methods, cfl, resos, params)

In [29]:
f1_zcpu = paramreso_z['cpu']
f1_zcpu

             EI          LE       EILE3D     EILE3DS      EIEALE          WY
16     0.963022    0.969707     2.226797    1.062637    0.908825    0.881817
32     7.947188    6.842240    16.066152    6.988953    6.582931    6.457352
64    47.274467   47.421073   123.956302   45.156720   50.637140   51.959568
128  529.370872  504.359521  1709.739155  578.138339  559.009905  534.779480

In [27]:
f1_zrec = paramreso_z['adv']
f1_zrec

            EI         LE      EILE3D    EILE3DS     EIEALE         WY
16    0.024783   0.024651    0.051886   0.024514   0.023400   0.023908
32    0.299730   0.286319    0.614353   0.310308   0.302205   0.299250
64    3.948528   3.591053    7.932511   3.749811   3.940967   4.294355
128  56.763691  47.170981  129.823390  59.641555  61.546707  60.292398